### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ddharshan** [thomashirtz/gym-hybrid#7]
Hi,
I was trying to run the code in Jupyter Notebook. However, I got an error as **AssertionError: Agent's minimum observation value is greater than it's maximum** when i run the codes that are inside the test folder. Would it be possible you to suggest me any comments for this error???

Thank you

**Comment by ddharshan** [comment]
Hi 
Could you please tell why this error occurs **AssertionError: Agent's minimum action value is greater than it's maximum**???

**Comment by ddharshan** [comment]
Hi
@PaParaZz1  Could you please tell why this error occurs AssertionError: Agent's minimum action value is greater than it's maximum???

**Comment by thomashirtz** [comment]
I would need a minimum reproducible code in order to know what is your issue

**Comment by ddharshan** [comment]
Thank you for your reply. I figured it out

**Comment by thomashirtz** [comment]
Can you explain what was the issue, and how you fixed it ?

**Comment by ddharshan** [comment]
> Can you explain what was the issue, and how you fixed it ?

Actually, i uninstalled the GitHub link and re-installed it. Finally it worked and couldn’t figure it out what was the exact issue.
